image: ubuntu

stages:
  - build

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get upgrade -qq
    - apt-get install -qq qemu-utils wget
  script: |
    ./alpine-make-vm-image \
      --image-format qcow2 \
      --image-size 2G \
      --repositories-file configure/repositories \
      --packages "$(cat configure/packages)" \
      --script-chroot \
      alpine-virthardened.qcow2 -- ./configure/setup.sh
  when: manual
