name: alpine make vm image

on: workflow_dispatch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v2

      - name: Build image
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --repositories-file configure/repositories \
              --packages "$(cat configure/packages)" \
              --script-chroot \
              alpine-virthardened.qcow2 -- ./configure/setup.sh

      - uses: actions/upload-artifact@v2
        with:
          path: alpine-virthardened.qcow2
