name: alpine

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - name: Build image
        run: |
          sudo ./alpine-make-vm-image \
            --image-format qcow2 \
            --image-size 2G \
            --repositories-file configure/repositories \
            --packages "$(cat configure/packages)" \
            --script-chroot \
            alpine.qcow2 -- ./configure/setup.sh

      - uses: actions/upload-artifact@v2
        with:
          name: alpine
          path: alpine.qcow2
